//
// Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
//
// On Wed Aug 19 17:32:47 EDT 2020
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module top_bsv(CLK,
	       RST_N);
  input  CLK;
  input  RST_N;

  // inlined wires
  wire [1 : 0] bram_serverAdapterA_s1_1$wget, bram_serverAdapterB_s1_1$wget;
  wire bram_serverAdapterA_cnt_1$whas,
       bram_serverAdapterA_outData_deqCalled$whas,
       bram_serverAdapterA_outData_enqData$whas,
       bram_serverAdapterA_outData_outData$whas,
       bram_serverAdapterB_cnt_1$whas,
       bram_serverAdapterB_outData_deqCalled$whas,
       bram_serverAdapterB_outData_enqData$whas,
       bram_serverAdapterB_outData_outData$whas,
       bram_serverAdapterB_writeWithResp$whas;

  // register bram_serverAdapterA_cnt
  reg [2 : 0] bram_serverAdapterA_cnt;
  wire [2 : 0] bram_serverAdapterA_cnt$D_IN;
  wire bram_serverAdapterA_cnt$EN;

  // register bram_serverAdapterA_s1
  reg [1 : 0] bram_serverAdapterA_s1;
  wire [1 : 0] bram_serverAdapterA_s1$D_IN;
  wire bram_serverAdapterA_s1$EN;

  // register bram_serverAdapterB_cnt
  reg [2 : 0] bram_serverAdapterB_cnt;
  wire [2 : 0] bram_serverAdapterB_cnt$D_IN;
  wire bram_serverAdapterB_cnt$EN;

  // register bram_serverAdapterB_s1
  reg [1 : 0] bram_serverAdapterB_s1;
  wire [1 : 0] bram_serverAdapterB_s1$D_IN;
  wire bram_serverAdapterB_s1$EN;

  // register cycle_count
  reg [31 : 0] cycle_count;
  wire [31 : 0] cycle_count$D_IN;
  wire cycle_count$EN;

  // register dreq
  reg [67 : 0] dreq;
  wire [67 : 0] dreq$D_IN;
  wire dreq$EN;

  // register ireq
  reg [67 : 0] ireq;
  wire [67 : 0] ireq$D_IN;
  wire ireq$EN;

  // ports of submodule bram_memory
  wire [31 : 0] bram_memory$DIA,
		bram_memory$DIB,
		bram_memory$DOA,
		bram_memory$DOB;
  wire [13 : 0] bram_memory$ADDRA, bram_memory$ADDRB;
  wire [3 : 0] bram_memory$WEA, bram_memory$WEB;
  wire bram_memory$ENA, bram_memory$ENB;

  // ports of submodule bram_serverAdapterA_outDataCore
  wire [31 : 0] bram_serverAdapterA_outDataCore$D_IN,
		bram_serverAdapterA_outDataCore$D_OUT;
  wire bram_serverAdapterA_outDataCore$CLR,
       bram_serverAdapterA_outDataCore$DEQ,
       bram_serverAdapterA_outDataCore$EMPTY_N,
       bram_serverAdapterA_outDataCore$ENQ,
       bram_serverAdapterA_outDataCore$FULL_N;

  // ports of submodule bram_serverAdapterB_outDataCore
  wire [31 : 0] bram_serverAdapterB_outDataCore$D_IN,
		bram_serverAdapterB_outDataCore$D_OUT;
  wire bram_serverAdapterB_outDataCore$CLR,
       bram_serverAdapterB_outDataCore$DEQ,
       bram_serverAdapterB_outDataCore$EMPTY_N,
       bram_serverAdapterB_outDataCore$ENQ,
       bram_serverAdapterB_outDataCore$FULL_N;

  // ports of submodule rv_core
  wire [67 : 0] rv_core$getDReq,
		rv_core$getDResp_a,
		rv_core$getIReq,
		rv_core$getIResp_a;
  wire rv_core$EN_getDReq,
       rv_core$EN_getDResp,
       rv_core$EN_getIReq,
       rv_core$EN_getIResp,
       rv_core$RDY_getDReq,
       rv_core$RDY_getDResp,
       rv_core$RDY_getIReq,
       rv_core$RDY_getIResp;

  // rule scheduling signals
  wire WILL_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq,
       WILL_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq,
       WILL_FIRE_RL_requestD;

  // remaining internal signals
  wire [31 : 0] x__h3413, x__h4235;
  wire [2 : 0] bram_serverAdapterA_cnt_6_PLUS_IF_bram_serverA_ETC___d32,
	       bram_serverAdapterB_cnt_5_PLUS_IF_bram_serverA_ETC___d91;
  wire [1 : 0] ab__h1432, ab__h2780;

  // submodule bram_memory
  BRAM2BELoad #(.FILENAME("mem.vmh"),
		.PIPELINED(1'd0),
		.ADDR_WIDTH(32'd14),
		.DATA_WIDTH(32'd32),
		.CHUNKSIZE(32'd8),
		.WE_WIDTH(32'd4),
		.MEMSIZE(15'd16384),
		.BINARY(1'd0)) bram_memory(.CLKA(CLK),
					   .CLKB(CLK),
					   .ADDRA(bram_memory$ADDRA),
					   .ADDRB(bram_memory$ADDRB),
					   .DIA(bram_memory$DIA),
					   .DIB(bram_memory$DIB),
					   .WEA(bram_memory$WEA),
					   .WEB(bram_memory$WEB),
					   .ENA(bram_memory$ENA),
					   .ENB(bram_memory$ENB),
					   .DOA(bram_memory$DOA),
					   .DOB(bram_memory$DOB));

  // submodule bram_serverAdapterA_outDataCore
  SizedFIFO #(.p1width(32'd32),
	      .p2depth(32'd3),
	      .p3cntr_width(32'd1),
	      .guarded(32'd1)) bram_serverAdapterA_outDataCore(.RST(RST_N),
							       .CLK(CLK),
							       .D_IN(bram_serverAdapterA_outDataCore$D_IN),
							       .ENQ(bram_serverAdapterA_outDataCore$ENQ),
							       .DEQ(bram_serverAdapterA_outDataCore$DEQ),
							       .CLR(bram_serverAdapterA_outDataCore$CLR),
							       .D_OUT(bram_serverAdapterA_outDataCore$D_OUT),
							       .FULL_N(bram_serverAdapterA_outDataCore$FULL_N),
							       .EMPTY_N(bram_serverAdapterA_outDataCore$EMPTY_N));

  // submodule bram_serverAdapterB_outDataCore
  SizedFIFO #(.p1width(32'd32),
	      .p2depth(32'd3),
	      .p3cntr_width(32'd1),
	      .guarded(32'd1)) bram_serverAdapterB_outDataCore(.RST(RST_N),
							       .CLK(CLK),
							       .D_IN(bram_serverAdapterB_outDataCore$D_IN),
							       .ENQ(bram_serverAdapterB_outDataCore$ENQ),
							       .DEQ(bram_serverAdapterB_outDataCore$DEQ),
							       .CLR(bram_serverAdapterB_outDataCore$CLR),
							       .D_OUT(bram_serverAdapterB_outDataCore$D_OUT),
							       .FULL_N(bram_serverAdapterB_outDataCore$FULL_N),
							       .EMPTY_N(bram_serverAdapterB_outDataCore$EMPTY_N));

  // submodule rv_core
  rv32_bsv rv_core(.CLK(CLK),
		   .RST_N(RST_N),
		   .getDResp_a(rv_core$getDResp_a),
		   .getIResp_a(rv_core$getIResp_a),
		   .EN_getIReq(rv_core$EN_getIReq),
		   .EN_getIResp(rv_core$EN_getIResp),
		   .EN_getDReq(rv_core$EN_getDReq),
		   .EN_getDResp(rv_core$EN_getDResp),
		   .getIReq(rv_core$getIReq),
		   .RDY_getIReq(rv_core$RDY_getIReq),
		   .RDY_getIResp(rv_core$RDY_getIResp),
		   .getDReq(rv_core$getDReq),
		   .RDY_getDReq(rv_core$RDY_getDReq),
		   .RDY_getDResp(rv_core$RDY_getDResp));

  // rule RL_requestD
  assign WILL_FIRE_RL_requestD =
	     rv_core$RDY_getDReq && (bram_serverAdapterA_cnt ^ 3'h4) < 3'd7 ;

  // rule RL_bram_serverAdapterA_outData_enqAndDeq
  assign WILL_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq =
	     bram_serverAdapterA_outDataCore$EMPTY_N &&
	     bram_serverAdapterA_outDataCore$FULL_N &&
	     bram_serverAdapterA_outData_deqCalled$whas &&
	     bram_serverAdapterA_outData_enqData$whas ;

  // rule RL_bram_serverAdapterB_outData_enqAndDeq
  assign WILL_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq =
	     bram_serverAdapterB_outDataCore$EMPTY_N &&
	     bram_serverAdapterB_outDataCore$FULL_N &&
	     bram_serverAdapterB_outData_deqCalled$whas &&
	     bram_serverAdapterB_outData_enqData$whas ;

  // inlined wires
  assign bram_serverAdapterA_outData_enqData$whas =
	     (!bram_serverAdapterA_s1[0] ||
	      bram_serverAdapterA_outDataCore$FULL_N) &&
	     bram_serverAdapterA_s1[1] &&
	     bram_serverAdapterA_s1[0] ;
  assign bram_serverAdapterA_outData_outData$whas =
	     bram_serverAdapterA_outDataCore$EMPTY_N ||
	     !bram_serverAdapterA_outDataCore$EMPTY_N &&
	     bram_serverAdapterA_outData_enqData$whas ;
  assign bram_serverAdapterA_cnt_1$whas =
	     rv_core$RDY_getDReq && (bram_serverAdapterA_cnt ^ 3'h4) < 3'd7 &&
	     (!ab__h1432[1] || ab__h1432[0]) ;
  assign bram_serverAdapterA_s1_1$wget =
	     { 1'd1, !ab__h1432[1] || ab__h1432[0] } ;
  assign bram_serverAdapterB_outData_enqData$whas =
	     (!bram_serverAdapterB_s1[0] ||
	      bram_serverAdapterB_outDataCore$FULL_N) &&
	     bram_serverAdapterB_s1[1] &&
	     bram_serverAdapterB_s1[0] ;
  assign bram_serverAdapterB_outData_outData$whas =
	     bram_serverAdapterB_outDataCore$EMPTY_N ||
	     !bram_serverAdapterB_outDataCore$EMPTY_N &&
	     bram_serverAdapterB_outData_enqData$whas ;
  assign bram_serverAdapterB_cnt_1$whas =
	     rv_core$RDY_getIReq && (bram_serverAdapterB_cnt ^ 3'h4) < 3'd7 &&
	     (!ab__h2780[1] || ab__h2780[0]) ;
  assign bram_serverAdapterB_writeWithResp$whas =
	     rv_core$RDY_getIReq && (bram_serverAdapterB_cnt ^ 3'h4) < 3'd7 ;
  assign bram_serverAdapterB_s1_1$wget =
	     { 1'd1, !ab__h2780[1] || ab__h2780[0] } ;
  assign bram_serverAdapterA_outData_deqCalled$whas =
	     rv_core$RDY_getDResp &&
	     (bram_serverAdapterA_outDataCore$EMPTY_N ||
	      bram_serverAdapterA_outData_enqData$whas) &&
	     bram_serverAdapterA_outData_outData$whas ;
  assign bram_serverAdapterB_outData_deqCalled$whas =
	     rv_core$RDY_getIResp &&
	     (bram_serverAdapterB_outDataCore$EMPTY_N ||
	      bram_serverAdapterB_outData_enqData$whas) &&
	     bram_serverAdapterB_outData_outData$whas ;

  // register bram_serverAdapterA_cnt
  assign bram_serverAdapterA_cnt$D_IN =
	     bram_serverAdapterA_cnt_6_PLUS_IF_bram_serverA_ETC___d32 ;
  assign bram_serverAdapterA_cnt$EN =
	     bram_serverAdapterA_cnt_1$whas ||
	     bram_serverAdapterA_outData_deqCalled$whas ;

  // register bram_serverAdapterA_s1
  assign bram_serverAdapterA_s1$D_IN =
	     { WILL_FIRE_RL_requestD && bram_serverAdapterA_s1_1$wget[1],
	       bram_serverAdapterA_s1_1$wget[0] } ;
  assign bram_serverAdapterA_s1$EN = 1'd1 ;

  // register bram_serverAdapterB_cnt
  assign bram_serverAdapterB_cnt$D_IN =
	     bram_serverAdapterB_cnt_5_PLUS_IF_bram_serverA_ETC___d91 ;
  assign bram_serverAdapterB_cnt$EN =
	     bram_serverAdapterB_cnt_1$whas ||
	     bram_serverAdapterB_outData_deqCalled$whas ;

  // register bram_serverAdapterB_s1
  assign bram_serverAdapterB_s1$D_IN =
	     { bram_serverAdapterB_writeWithResp$whas &&
	       bram_serverAdapterB_s1_1$wget[1],
	       bram_serverAdapterB_s1_1$wget[0] } ;
  assign bram_serverAdapterB_s1$EN = 1'd1 ;

  // register cycle_count
  assign cycle_count$D_IN = cycle_count + 32'd1 ;
  assign cycle_count$EN = 1'd1 ;

  // register dreq
  assign dreq$D_IN = rv_core$getDReq ;
  assign dreq$EN = WILL_FIRE_RL_requestD ;

  // register ireq
  assign ireq$D_IN = rv_core$getIReq ;
  assign ireq$EN = bram_serverAdapterB_writeWithResp$whas ;

  // submodule bram_memory
  assign bram_memory$ADDRA = rv_core$getDReq[47:34] ;
  assign bram_memory$ADDRB = rv_core$getIReq[47:34] ;
  assign bram_memory$DIA = rv_core$getDReq[31:0] ;
  assign bram_memory$DIB = rv_core$getIReq[31:0] ;
  assign bram_memory$WEA = rv_core$getDReq[67:64] ;
  assign bram_memory$WEB = rv_core$getIReq[67:64] ;
  assign bram_memory$ENA = WILL_FIRE_RL_requestD ;
  assign bram_memory$ENB = bram_serverAdapterB_writeWithResp$whas ;

  // submodule bram_serverAdapterA_outDataCore
  assign bram_serverAdapterA_outDataCore$D_IN = bram_memory$DOA ;
  assign bram_serverAdapterA_outDataCore$ENQ =
	     WILL_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq ||
	     bram_serverAdapterA_outDataCore$FULL_N &&
	     !bram_serverAdapterA_outData_deqCalled$whas &&
	     bram_serverAdapterA_outData_enqData$whas ;
  assign bram_serverAdapterA_outDataCore$DEQ =
	     WILL_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq ||
	     bram_serverAdapterA_outDataCore$EMPTY_N &&
	     bram_serverAdapterA_outData_deqCalled$whas &&
	     !bram_serverAdapterA_outData_enqData$whas ;
  assign bram_serverAdapterA_outDataCore$CLR = 1'b0 ;

  // submodule bram_serverAdapterB_outDataCore
  assign bram_serverAdapterB_outDataCore$D_IN = bram_memory$DOB ;
  assign bram_serverAdapterB_outDataCore$ENQ =
	     WILL_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq ||
	     bram_serverAdapterB_outDataCore$FULL_N &&
	     !bram_serverAdapterB_outData_deqCalled$whas &&
	     bram_serverAdapterB_outData_enqData$whas ;
  assign bram_serverAdapterB_outDataCore$DEQ =
	     WILL_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq ||
	     bram_serverAdapterB_outDataCore$EMPTY_N &&
	     bram_serverAdapterB_outData_deqCalled$whas &&
	     !bram_serverAdapterB_outData_enqData$whas ;
  assign bram_serverAdapterB_outDataCore$CLR = 1'b0 ;

  // submodule rv_core
  assign rv_core$getDResp_a = { dreq[67:32], x__h4235 } ;
  assign rv_core$getIResp_a = { ireq[67:32], x__h3413 } ;
  assign rv_core$EN_getIReq =
	     rv_core$RDY_getIReq && (bram_serverAdapterB_cnt ^ 3'h4) < 3'd7 ;
  assign rv_core$EN_getIResp =
	     rv_core$RDY_getIResp &&
	     (bram_serverAdapterB_outDataCore$EMPTY_N ||
	      bram_serverAdapterB_outData_enqData$whas) &&
	     bram_serverAdapterB_outData_outData$whas ;
  assign rv_core$EN_getDReq = WILL_FIRE_RL_requestD ;
  assign rv_core$EN_getDResp =
	     rv_core$RDY_getDResp &&
	     (bram_serverAdapterA_outDataCore$EMPTY_N ||
	      bram_serverAdapterA_outData_enqData$whas) &&
	     bram_serverAdapterA_outData_outData$whas ;

  // remaining internal signals
  assign ab__h1432 = { rv_core$getDReq[67:64] != 4'd0, 1'd1 } ;
  assign ab__h2780 = { rv_core$getIReq[67:64] != 4'd0, 1'd1 } ;
  assign bram_serverAdapterA_cnt_6_PLUS_IF_bram_serverA_ETC___d32 =
	     bram_serverAdapterA_cnt +
	     (bram_serverAdapterA_cnt_1$whas ? 3'd1 : 3'd0) +
	     (bram_serverAdapterA_outData_deqCalled$whas ? 3'd7 : 3'd0) ;
  assign bram_serverAdapterB_cnt_5_PLUS_IF_bram_serverA_ETC___d91 =
	     bram_serverAdapterB_cnt +
	     (bram_serverAdapterB_cnt_1$whas ? 3'd1 : 3'd0) +
	     (bram_serverAdapterB_outData_deqCalled$whas ? 3'd7 : 3'd0) ;
  assign x__h3413 =
	     bram_serverAdapterB_outDataCore$EMPTY_N ?
	       bram_serverAdapterB_outDataCore$D_OUT :
	       bram_memory$DOB ;
  assign x__h4235 =
	     bram_serverAdapterA_outDataCore$EMPTY_N ?
	       bram_serverAdapterA_outDataCore$D_OUT :
	       bram_memory$DOA ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        bram_serverAdapterA_cnt <= `BSV_ASSIGNMENT_DELAY 3'd0;
	bram_serverAdapterA_s1 <= `BSV_ASSIGNMENT_DELAY 2'd0;
	bram_serverAdapterB_cnt <= `BSV_ASSIGNMENT_DELAY 3'd0;
	bram_serverAdapterB_s1 <= `BSV_ASSIGNMENT_DELAY 2'd0;
	cycle_count <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (bram_serverAdapterA_cnt$EN)
	  bram_serverAdapterA_cnt <= `BSV_ASSIGNMENT_DELAY
	      bram_serverAdapterA_cnt$D_IN;
	if (bram_serverAdapterA_s1$EN)
	  bram_serverAdapterA_s1 <= `BSV_ASSIGNMENT_DELAY
	      bram_serverAdapterA_s1$D_IN;
	if (bram_serverAdapterB_cnt$EN)
	  bram_serverAdapterB_cnt <= `BSV_ASSIGNMENT_DELAY
	      bram_serverAdapterB_cnt$D_IN;
	if (bram_serverAdapterB_s1$EN)
	  bram_serverAdapterB_s1 <= `BSV_ASSIGNMENT_DELAY
	      bram_serverAdapterB_s1$D_IN;
	if (cycle_count$EN)
	  cycle_count <= `BSV_ASSIGNMENT_DELAY cycle_count$D_IN;
      end
    if (dreq$EN) dreq <= `BSV_ASSIGNMENT_DELAY dreq$D_IN;
    if (ireq$EN) ireq <= `BSV_ASSIGNMENT_DELAY ireq$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    bram_serverAdapterA_cnt = 3'h2;
    bram_serverAdapterA_s1 = 2'h2;
    bram_serverAdapterB_cnt = 3'h2;
    bram_serverAdapterB_s1 = 2'h2;
    cycle_count = 32'hAAAAAAAA;
    dreq = 68'hAAAAAAAAAAAAAAAAA;
    ireq = 68'hAAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (bram_serverAdapterA_s1[1] &&
	  !bram_serverAdapterA_outDataCore$FULL_N)
	$display("ERROR: %m: mkBRAMSeverAdapter overrun");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_requestD && rv_core$getDReq[67:64] == 4'hF &&
	  rv_core$getDReq[63:32] == 32'h40000000)
	$fwrite(32'h80000002, "%c", rv_core$getDReq[7:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_requestD && rv_core$getDReq[67:64] == 4'hF &&
	  rv_core$getDReq[63:32] == 32'h40000000)
	$fflush(32'h80000002);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_requestD && rv_core$getDReq[67:64] == 4'hF &&
	  rv_core$getDReq[63:32] == 32'h40000004)
	$fwrite(32'h80000002, "%0d", rv_core$getDReq[31:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_requestD && rv_core$getDReq[67:64] == 4'hF &&
	  rv_core$getDReq[63:32] == 32'h40000004)
	$fflush(32'h80000002);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_requestD && rv_core$getDReq[67:64] == 4'hF &&
	  rv_core$getDReq[63:32] == 32'h40001000 &&
	  rv_core$getDReq[31:0] == 32'd0)
	$fdisplay(32'h80000002, "  \033[0;32mPASS\033[0m");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_requestD && rv_core$getDReq[67:64] == 4'hF &&
	  rv_core$getDReq[63:32] == 32'h40001000 &&
	  rv_core$getDReq[31:0] != 32'd0)
	$fdisplay(32'h80000002,
		  "  \033[0;31mFAIL\033[0m (%0d)",
		  rv_core$getDReq[31:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_requestD && rv_core$getDReq[67:64] == 4'hF &&
	  rv_core$getDReq[63:32] == 32'h40001000)
	$fflush(32'h80000002);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_requestD && rv_core$getDReq[67:64] == 4'hF &&
	  rv_core$getDReq[63:32] == 32'h40001000)
	$finish(32'd1);
    if (RST_N != `BSV_RESET_VALUE)
      if (bram_serverAdapterB_s1[1] &&
	  !bram_serverAdapterB_outDataCore$FULL_N)
	$display("ERROR: %m: mkBRAMSeverAdapter overrun");
  end
  // synopsys translate_on
endmodule  // top_bsv

