#!/usr/bin/env sh
# This script exists because dune doesn't support multi-library Coq projects.
# The alternative would be to `dune build @install` the Coq library every time,
# but the proofs are slow and not needed by the tests and examples.

[ "$COQDEP" != "" ] ||
    { echo "COQDEP variable unset" > /dev/stderr; exit 1; }
[ "$COQDEP_BUILD_DIR" != "" ] ||
    { echo "COQDEP_BUILD_DIR variable unset" > /dev/stderr; exit 1; }

case "$@" in
    *"-R . Koika"*) "$COQDEP" "$@";;
    *) "$COQDEP" -R "$COQDEP_BUILD_DIR" Koika "$@"
esac
